import assert from 'node:assert/strict';
import test from 'node:test';
import { buildWorkOrderPatrolRoute, haversineDistanceKm } from '../src/patrol';
import type { AdminReport, PatrolOptions, WorkOrder } from '../src/types';

const START = { lat: 22.38, lng: 114.18 };
const OPTIONS: PatrolOptions = { travelMode: 'inspection-walking', taskGroup: 'verification', maxStops: 8, serviceMinutesPerStop: 12 };
function makeReport(id: string, index: number): AdminReport { return { id, location: `示範地點 ${index}`, description: '單車阻塞通道', date: '2026-07-15', status: 'classified', lat: 22.38 + index * 0.001, lng: 114.18 + index * 0.001, locationSource: 'gps', caseType: 'obstruction', urgency: 'urgent', procedureConfirmed: true, coordinatesValid: true, isDuplicate: false }; }
function makeOrder(id: string, caseId: string, patch: Partial<WorkOrder> = {}): WorkOrder { return { id, caseId, taskType: 'site_verification', title: id, leadDepartment: 'FEHD', supportingDepartments: [], location: '沙田', district: '沙田', assignedTeamId: 'team-fehd', scheduledAt: '2026-07-15T09:00:00.000Z', priority: 'urgent', prerequisiteWorkOrderIds: [], requiredCapabilities: [], requiredEquipment: [], evidenceChecklist: [], status: 'scheduled', assignmentHistory: [], createdAt: '2026-07-15T08:00:00.000Z', updatedAt: '2026-07-15T08:00:00.000Z', ...patch }; }
function makeData(count: number): { reports: AdminReport[]; orders: WorkOrder[] } { const reports = Array.from({ length: count }, (_, index) => makeReport(`case-${index}`, index)); return { reports, orders: reports.map((report, index) => makeOrder(`wo-${index}`, report.id)) }; }

test('patrol planner selects at most the configured five to eight work orders', () => { const { reports, orders } = makeData(9); const route = buildWorkOrderPatrolRoute(START, orders, reports, { ...OPTIONS, maxStops: 5 }, 'FEHD', '2026-07-15'); assert.equal(route.workOrderIds.length, 5); assert.equal(route.algorithm, 'nearest-neighbor-2opt'); });
test('same inputs produce the same order and 2-opt does not increase distance', () => { const { reports, orders } = makeData(6); const first = buildWorkOrderPatrolRoute(START, orders, reports, OPTIONS, 'FEHD', '2026-07-15'); const second = buildWorkOrderPatrolRoute(START, orders, reports, OPTIONS, 'FEHD', '2026-07-15'); assert.deepEqual(first.workOrderIds, second.workOrderIds); assert.equal(first.estimatedDistanceKm <= first.initialDistanceKm, true); });
test('route draft uses a limitation label when no map route is available', () => { const { reports, orders } = makeData(2); const route = buildWorkOrderPatrolRoute(START, orders, reports, { ...OPTIONS, routeSource: 'straight-line-estimate' }, 'FEHD', '2026-07-15'); assert.equal(route.routeSource, 'straight-line-estimate'); assert.equal(haversineDistanceKm(START, START), 0); });
test('not-ready work orders and reports without valid coordinates are excluded', () => { const { reports, orders } = makeData(2); reports[1].coordinatesValid = false; const route = buildWorkOrderPatrolRoute(START, [...orders, makeOrder('draft', 'case-0', { status: 'draft' })], reports, OPTIONS, 'FEHD', '2026-07-15'); assert.deepEqual(route.workOrderIds, ['wo-0']); });
