import { useMemo, useState } from 'react';
import { buildWorkOrderPatrolRoute } from '../patrol';
import type { AdminReport, DepartmentCode, PatrolOptions, PatrolRouteDraft, WorkOrder } from '../types';

interface PatrolPlannerProps { reports: AdminReport[]; workOrders: WorkOrder[]; onConfirm: (route: PatrolRouteDraft) => void; }
const departments: DepartmentCode[] = ['HAD', 'TD', 'LandsD', 'FEHD', 'HKPF'];
const taskLabels = { verification: '現場核實', notice: '通知／封鎖', removal: '移走／保管' } as const;

export default function PatrolPlanner({ reports, workOrders, onConfirm }: PatrolPlannerProps) {
  const defaultDate = useMemo(() => workOrders.find((order) => order.status === 'scheduled' && order.scheduledAt)?.scheduledAt?.slice(0, 10) ?? '', [workOrders]);
  const [department, setDepartment] = useState<DepartmentCode>('FEHD');
  const [actionDate, setActionDate] = useState(defaultDate);
  const [taskGroup, setTaskGroup] = useState<PatrolOptions['taskGroup']>('verification');
  const [travelMode, setTravelMode] = useState<PatrolOptions['travelMode']>('inspection-walking');
  const [maxStops, setMaxStops] = useState(5);
  const [planningAt, setPlanningAt] = useState(() => new Date().toISOString());
  const [route, setRoute] = useState<PatrolRouteDraft | null>(null);
  const eligibleCount = useMemo(() => workOrders.filter((order) => order.status === 'scheduled' && order.leadDepartment === department && order.scheduledAt?.slice(0, 10) === actionDate).length, [workOrders, department, actionDate]);
  const generate = () => setRoute(buildWorkOrderPatrolRoute({ lat: 22.38, lng: 114.18 }, workOrders, reports, { travelMode, taskGroup, maxStops, serviceMinutesPerStop: 12, routeSource: 'straight-line-estimate' }, department, actionDate, planningAt || undefined));
  return <section className="bg-white border border-zinc-200 rounded-2xl p-4 space-y-4">
    <div><div className="flex items-center gap-2"><h3 className="text-base font-black text-zinc-900">已排期工作單巡邏路線</h3><span className="text-[10px] rounded-full bg-amber-100 text-amber-800 px-2 py-1 font-bold">Prototype Simulation</span></div><p className="text-[11px] text-zinc-500 mt-1">只納入已排期、結構準備完成及有有效案件座標的工作單，目前候選 {eligibleCount} 張。</p></div>
    <div className="grid grid-cols-2 md:grid-cols-6 gap-2"><label className="text-[11px] text-zinc-600">部門<select value={department} onChange={(e) => setDepartment(e.target.value as DepartmentCode)} className="mt-1 w-full rounded-lg border border-zinc-200 bg-zinc-50 px-2 py-2 text-xs">{departments.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-[11px] text-zinc-600">行動日期<input type="date" value={actionDate} onChange={(e) => setActionDate(e.target.value)} className="mt-1 w-full rounded-lg border border-zinc-200 bg-zinc-50 px-2 py-2 text-xs" /></label><label className="text-[11px] text-zinc-600">規劃時間<input type="datetime-local" value={planningAt.slice(0, 16)} onChange={(e) => { const parsed = new Date(e.target.value); setPlanningAt(Number.isFinite(parsed.getTime()) ? parsed.toISOString() : ''); }} className="mt-1 w-full rounded-lg border border-zinc-200 bg-zinc-50 px-2 py-2 text-xs" /></label><label className="text-[11px] text-zinc-600">工作群組<select value={taskGroup} onChange={(e) => { const group = e.target.value as PatrolOptions['taskGroup']; setTaskGroup(group); if (group === 'removal') setTravelMode('clearance-vehicle'); else if (travelMode === 'clearance-vehicle') setTravelMode('inspection-driving'); }} className="mt-1 w-full rounded-lg border border-zinc-200 bg-zinc-50 px-2 py-2 text-xs">{Object.entries(taskLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="text-[11px] text-zinc-600">交通模式<select value={travelMode} onChange={(e) => setTravelMode(e.target.value as PatrolOptions['travelMode'])} className="mt-1 w-full rounded-lg border border-zinc-200 bg-zinc-50 px-2 py-2 text-xs"><option value="inspection-walking">步行巡查</option><option value="inspection-driving">一般駕駛巡查</option><option value="clearance-vehicle">清理車輛</option></select></label><label className="text-[11px] text-zinc-600">最多工作單<select value={maxStops} onChange={(e) => setMaxStops(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-zinc-200 bg-zinc-50 px-2 py-2 text-xs">{[5, 6, 7, 8].map((value) => <option key={value} value={value}>{value} 張</option>)}</select></label></div>
    <button type="button" onClick={generate} className="w-full rounded-xl bg-[#006b2c] text-white py-2.5 text-xs font-bold hover:bg-[#005320]">產生工作單路線</button>
    {route && <div className="space-y-3 text-xs"><div className="grid grid-cols-3 gap-2"><div className="rounded-lg bg-zinc-50 p-2"><p className="text-zinc-500">工作單</p><p className="font-black text-zinc-900">{route.workOrderIds.length} 張</p></div><div className="rounded-lg bg-zinc-50 p-2"><p className="text-zinc-500">估算距離</p><p className="font-black text-zinc-900">{route.estimatedDistanceKm} km</p></div><div className="rounded-lg bg-zinc-50 p-2"><p className="text-zinc-500">估算時間</p><p className="font-black text-zinc-900">{route.estimatedTravelMinutesRange.min}–{route.estimatedTravelMinutesRange.max} 分</p></div></div><ol className="space-y-1.5">{route.orderedStops.map((stop) => <li key={stop.workOrderId} className="rounded-lg bg-zinc-50 px-3 py-2 flex justify-between"><span>{stop.order}. {workOrders.find((order) => order.id === stop.workOrderId)?.title || reports.find((report) => report.id === stop.caseId)?.location || stop.workOrderId}</span><span className="text-zinc-500">優先度 {stop.priorityScore}</span></li>)}</ol><p className="text-amber-700 leading-relaxed">本結果只供示範；確認後只會更新路線內工作單及審計記錄，不會自動變更案件狀態。</p><button type="button" disabled={route.workOrderIds.length === 0} onClick={() => onConfirm(route)} className="w-full rounded-xl border border-[#006b2c] text-[#006b2c] py-2.5 font-bold disabled:opacity-40">確認工作單路線</button></div>}
  </section>;
}
